# Generated by Django 5.2.5 on 2025-08-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_generalsettings_generalsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=254)),
                ('description', models.TextField(blank=True, default='', max_length=254)),
                ('file', models.ImageField(blank=True, default='', upload_to='images/', verbose_name='Image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='generalsetting',
            options={'ordering': ['name'], 'verbose_name': 'General Setting', 'verbose_name_plural': 'General Settings'},
        ),
    ]
