# Generated by Django 5.2.5 on 2025-08-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
