# Generated by Django 5.2.5 on 2025-09-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['link'], 'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Medias'},
        ),
    ]
