# Generated by Django 5.2.5 on 2025-09-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_socialmedia_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Social Media Order'),
        ),
    ]
