# Generated by Django 5.2.5 on 2025-09-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=254, verbose_name='Slug'),
        ),
    ]
