# Generated by Django 5.2.5 on 2025-09-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', help_text='Enter your name', max_length=254, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', help_text='Enter your email', max_length=254, verbose_name='Email')),
                ('subject', models.CharField(blank=True, default='', help_text='Enter your subject', max_length=254, verbose_name='Subject')),
                ('message', models.TextField(blank=True, default='', help_text='Enter your message', max_length=254, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
